apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.service_name }}
  labels:
    app: {{ .Values.backend.service_name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.backend.service_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.service_name }}
    spec:
      restartPolicy: Always
      initContainers:
      - name: perms-fixer
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        command: ["sh","-c","chown -R www-data:www-data /var/www/html/public/uploads"]
        volumeMounts:
{{ if eq .Values.env "staging" }}
          - name: uploads-volume
{{ end }}
{{ if eq .Values.env "production" }}
          - name: prod-uploads
{{ end }}
            mountPath: /var/www/html/public/uploads
      containers:
      - name: {{ .Values.backend.service_name }}
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        imagePullPolicy: Always
        volumeMounts:
{{ if eq .Values.env "staging" }}
          - name: uploads-volume
{{ end }}
{{ if eq .Values.env "production" }}
          - name: prod-uploads
{{ end }}
            mountPath: /var/www/html/public/uploads
        resources:
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 3
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
{{ if eq .Values.env "staging" }}
            claimName: uploads-volume
{{ end }}
{{ if eq .Values.env "production" }}
            claimName: prod-uploads
{{ end }}
      imagePullSecrets:
      - name: "utils-docker"
