apiVersion: batch/v1
kind: CronJob
metadata:
  name: queue-work
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: queue-work
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - php
            - artisan course:completed
          restartPolicy: OnFailure
