apiVersion: batch/v1
kind: CronJob
metadata:
  name: course-completed
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: course-completed
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /usr/bin/php 
            - artisan
            - course:completed
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: assignment-completed
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: assignment-completed
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /usr/bin/php 
            - artisan
            - assignment:completed
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: course-reminder
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: course-reminder
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /usr/bin/php 
            - artisan
            - course:reminder
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: assignment-deadline
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: assignment-deadline
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /usr/bin/php 
            - artisan
            - assignment:deadline
          restartPolicy: Never
#---
#apiVersion: batch/v1
#kind: CronJob
#metadata:
#  name: class-cron
#spec:
#  schedule: "* * * * *"
#  successfulJobsHistoryLimit: 0
#  failedJobsHistoryLimit: 0
#  jobTemplate:
#    spec:
#      template:
#        spec:
#          containers:
#          - name: class-cron
#            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
#            imagePullPolicy: IfNotPresent
#            command:
#            - /usr/bin/php 
#            - artisan
#            - class:cron
#          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: queue-work
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: queue-work
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /usr/bin/php 
            - artisan
            - queue:work
            - --stop-when-empty
          restartPolicy: Never
---
