apiVersion: batch/v1
kind: CronJob
metadata:
  name: course-completed
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: course-completed
            image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
            imagePullPolicy: IfNotPresent
            command:
            - /usr/bin/php 
            - artisan
            - course:completed
          restartPolicy: OnFailure
