apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service_name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.service_name }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: {{ .Values.frontend.service_name }}