kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: uploads-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gluster-heketi-external
  resources:
    requests:
      storage: {{ .Values.backend.uploads_storage }}
