kind: PersistentVolumeClaim
apiVersion: v1
metadata:

{{ if eq .Values.env "staging" }}
  name: uploads-volume
{{ end }}
{{ if eq .Values.env "production" }}
  name: prod-uploads
{{ end }}

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: gluster-heketi-external
  resources:
    requests:
      storage: {{ .Values.backend.uploads_storage }}
